### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for '0' in ,

### ISSUE THREAD

**Issue by esbanarango** [xoxco/jQuery-Tags-Input#253] opened 2015-05-29 21:36 UTC
Hello and Thank you for this project!

I'm using `jQuery-Tags-Input` with jQuery 2.1.3 and I'm getting this error when hitting `,`:

`Uncaught TypeError: Cannot use 'in' operator to search for '0' in ,`

It references this:
````js
//Line 367
$.each(event.data.delimiter ,function(index, value){
    if(event.which == value.charCodeAt(0)){
        flag = true;
    }
});
````

**Comment by lucknerjb** [comment] 2015-05-29 21:38
Duplicate of #223. I'm starting to think that this may have to do with the version of jquery and not the change that we implemented. Let me give this a shot with 2.1.x and see what happens

**Comment by lucknerjb** [comment] 2015-05-29 22:09
I see your PR, but when trying it out with 2.1.3, I don't get any errors. Can you confirm that's the version that you are using?

**Comment by esbanarango** [comment] 2015-05-29 22:11
mmmm just double checked. `jQuery JavaScript Library v2.1.3`

**Comment by lucknerjb** [comment] 2015-05-29 22:14
Can you create a jsfiddle replicating the issue so I can play around with it? I'd like to find out why you're seeing this issue and I am not... it's weird

**Comment by esbanarango** [comment] 2015-05-29 22:14
@lucknerjb Sure!

**Comment by lucknerjb** [comment] 2015-05-29 22:17
ah! actually, I managed to replicate it. I just realized I was working in an older local branch which was using
```
for (delimiter in event.data.delimiter)
```

instead of 
```
$.each(event.data.delimiter)
```

**Comment by lucknerjb** [comment] 2015-05-29 22:21
I'll close your PR and push a change that should cover the scenario where folks have manually set their delimiters to be a string when the initialize the plugin as your change would break that.

Thanks for helping clear this issue though!

**Comment by esbanarango** [comment] 2015-05-29 22:21
@lucknerjb Thank you!!

**Comment by lucknerjb** [comment] 2015-05-29 22:28
No prob at all :-)

**Closed by lucknerjb** 2015-05-29 22:28 UTC
